CREATE TABLE Users (
    UserId INTEGER PRIMARY KEY AUTOINCREMENT,
    UserName TEXT NOT NULL
);
CREATE TABLE GameScores (
    ScoreId INTEGER PRIMARY KEY AUTOINCREMENT,
    UserName TEXT,
    GameType TEXT,
    Score INTEGER,
    PlayTime DATETIME DEFAULT CURRENT_TIMESTAMP
);